{{- $app := index .Values (.Release.Name | replace "-" "_") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "base-chart.name" . }}
    helm.sh/chart: {{ include "base-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with $app.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k | quote }}: {{ $v | quote }}
    {{- end -}}
  {{- end }}
spec:
  replicas: {{ $app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if $app.nodeSelector }}
      nodeSelector:
      {{- toYaml $app.nodeSelector | indent 8 }}
    {{- end }}
    {{- if $app.affinity }}
      affinity:
      {{- toYaml $app.affinity | indent 8 }}
    {{- end }}
    {{- if $app.securityContext }}
      securityContext:
      {{- toYaml $app.securityContext | indent 8 }}
    {{- end }}
    {{- if $app.tolerations }}
      tolerations:
      {{- toYaml $app.tolerations | indent 8 }}
    {{- end }}
      enableServiceLinks: {{ $app.enableServiceLinks }}
      containers:
        - name: {{ include "base-chart.name" . }}
          image: "{{ required "Must specify image.repository field in values" $app.image.repository }}:{{ required "Must specify image.tag field in values" $app.image.tag }}"
          imagePullPolicy: {{ $app.imagePullPolicy }}
          {{- with $app.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $app.env }}
          env:
            {{- range $ename, $evalue := . }}
            - name: {{ $ename | quote }}
              value: {{ $evalue | quote }}
            {{- end }}
          {{- end }}
          {{- with $app.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
