apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "base-chart.name" . }}
    helm.sh/chart: {{ include "base-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k | quote }}: {{ $v | quote }}
    {{- end -}}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.securityContext }}
      securityContext:
      {{- toYaml .Values.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      containers:
        - name: {{ include "base-chart.name" . }}
          image: "{{ required "Must specify image.repository field in values" .Values.image.repository }}:{{ required "Must specify image.tag field in values" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $ename, $evalue := . }}
            - name: {{ $ename | quote }}
              value: {{ $evalue | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
